# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    volumes:
      - ./:/app
    environment:
      - OLLAMA_ADDRESS=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]

volumes:
  ollama-data:
